name: CI

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - w1jtoo
    - development
    - faceless

jobs:
  build-windows:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: dotnet build Tests\Tests\
  test-windows:
    needs: build-windows
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: dotnet test Tests\Tests\
      
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: dotnet build Tests/Tests/
  test-ubuntu:
    needs: build-ubuntu
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: dotnet test Tests/Tests/
